# .gitlab-ci.yml
stages:
  - build
  - test
  - smoke

variables:
  IMAGE_NAME: "logistics-etl:smoke"
  CONTAINER_NAME: "etl-smoke"

# Stage 1: Build Docker image
build:
  stage: build
  image: docker:24.0.5  # версия Docker CLI
  services:
    - docker:24.0.5-dind
  script:
    - docker build -t $IMAGE_NAME .

# Stage 2: Run unit tests
unit_tests:
  stage: test
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker run --rm $IMAGE_NAME pytest

# Stage 3: Run container and smoke test
smoke_test:
  stage: smoke
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker run -d --name $CONTAINER_NAME $IMAGE_NAME
    - sleep 5
    - docker exec $CONTAINER_NAME curl -f http://127.0.0.1:8000/health