name: Diabetes ETL Smoke Test Pipeline

on:
  push:
    branches: [ main ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t diabetes-etl:smoke .

      - name: Run container
        run: |
          docker run -d --name etl-smoke diabetes-etl:smoke
          sleep 5  # ждём, пока FastAPI сервис поднимется

      - name: Smoke test (health check)
        run: docker exec etl-smoke curl -f http://127.0.0.1:8000/health