name: smoke-test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t diabetes-etl:smoke .

      - name: Start container
        run: |
          docker run -d --name diabetes-etl-test diabetes-etl:smoke

      - name: Check /health endpoint
        run: |
          curl -s http://localhost:8000/health

      - name: Run Pytest
        run: |
          docker exec diabetes-etl-test pytest --maxfail=1 --disable-warnings -q